use_frameworks!

platform :ios, '8.0'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'YLBFlutterDemo_Example' do
  
  install_all_flutter_pods(flutter_application_path)
  
  pod 'YLBFlutterDemo', :path => '../'

  target 'YLBFlutterDemo_Tests' do
    inherit! :search_paths

    
  end
end
